M48
; DRILL file {KiCad 7.0.8} date 2023 October 26, Thursday 13:24:27
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-26T13:24:27+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.1535Y-4.1535
X4.1535Y-7.6575
X6.063Y-7.3622
X7.6575Y-4.1535
T0
M30
