M48
; DRILL file {KiCad 7.0.8} date 2023 October 17, Tuesday 18:42:53
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-17T18:42:53+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.8228Y-5.374
X4.8228Y-6.2795
X6.9882Y-5.374
X6.9882Y-6.2795
T0
M30
