M48
; DRILL file {KiCad 7.0.8} date 2023 November 22, Wednesday 21:49:48
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-22T21:49:48+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0866
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1260
%
G90
G05
T1
X4.3307Y-4.7244
X4.3307Y-7.0866
T2
X5.9055Y-4.1339
X5.9055Y-7.6772
X7.874Y-5.9055
T0
M30
