M48
; DRILL file {KiCad 7.0.8} date 2023 November 12, Sunday 08:49:25
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-11-12T08:49:25+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.0551Y-5.9055
X5.9055Y-4.0551
X5.9055Y-7.7559
X7.7559Y-5.9055
T0
M30
