M48
; DRILL file {KiCad 7.0.8} date 2023 October 26, Thursday 13:22:38
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2023-10-26T13:22:38+11:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.8
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.1260
%
G90
G05
T1
X4.4094Y-5.9055
X5.3051Y-7.2835
X5.9055Y-4.4094
X6.5059Y-7.2835
X7.4016Y-5.9055
T0
M30
